version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "84:80"
    networks:
      - appnet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "86:80"
    environment:
      - DB_HOST=book-rds.c1u4kewc6r37.ap-south-1.rds.amazonaws.com
      - DB_USERNAME=root
      - DB_PASSWORD=Cloud123
      - PORT=3306
    networks:
      - appnet

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cloud123
      MYSQL_DATABASE: yourdbname
    ports:
      - "3306:3306"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
